name: Android Build
on:
  push:
    branches:  [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Create Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      - name: Start Android Release Build APK
        run: flutter build apk
      - name: Start Android Release Build AppBundle
        run: flutter build appbundle
      - name: Copy APK and AppBundle to directory
        run: |
          cp build/app/outputs/flutter-apk/app-release.apk build/android/
          cp build/app/outputs/bundle/release/app-release.aab build/android/

      # Step to commit the generated APK and AppBundle
      - name: Commit APK and AppBundle
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add build/android/.
          git commit -m "Add APK and AppBundle for release [skip ci]"

      # Step to create a tag for the release
      - name: Create Release Tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          NEW_TAG="v${TAG}"
          git tag $NEW_TAG
          git push origin $NEW_TAG
