name: Android Build
on:
  push:
    branches:  [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Create Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      - name: Start Android Release Build APK
        run: flutter build apk
      - name: Start Android Release Build AppBundle
        run: flutter build appbundle
